In [1]:
import numpy as np

# (a) Creating Numpy Array

In [3]:
# (i) Single Dimensional Array

n1=np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [2]:
# (ii) Multi Dimensional Array

n2=np.array([[10,20,30,40],[50,60,70,80]])
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# (b) Initializing Numpy Array

In [5]:
# (i) Initializing Numpy Array with zeros

n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [6]:
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
n1=np.zeros((5,7))
n1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# (c) Initializing Numpy Array with same number

In [10]:
n1=np.full((3,3),10)
n1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [11]:
n2=np.full((4,3),11)
n2

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

# (d) Initializing Numpy Array within a range

In [8]:
n1=np.arange(10,21)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
n1=np.arange(10,130,10)  # There last one number which is 10 is difference in array
n1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

# (e) Initializing Numpy Array with random numbers

In [12]:
n1=np.random.randint(1,100,5)
n1

array([83, 57,  5, 66, 88])

# (f) Checking the shape of Numpy Array

In [13]:
n1=np.array(([10,20,30],[10,20,30]))
n1
n1.shape

(2, 3)

# (g) Changing the shape of Numpy Array

In [14]:
n1.shape=(3,2)
n1.shape

(3, 2)

In [15]:
n1

array([[10, 20],
       [30, 10],
       [20, 30]])

# (h) Joining Numpy Array

In [3]:
# (i) v stack() - For vertical arrangement of array

n1=np.array([45,85,96])
n2=np.array([12,21,10])
np.vstack((n1,n2))

array([[45, 85, 96],
       [12, 21, 10]])

In [4]:
# (ii) h stack() - For horizontal arrangement of array

n1=np.array([45,85,96])
n2=np.array([12,21,10])
np.hstack((n1,n2))

array([45, 85, 96, 12, 21, 10])

In [5]:
# (iii) column_stack()

np.column_stack((n1,n2))

array([[45, 12],
       [85, 21],
       [96, 10]])

# (i) Numpy intersection and Difference

In [6]:
# (i) Numpy Intersection - 2 Numpy array main se common numbers alag karne ke liye use hota h

n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.intersect1d (n1,n2)

array([50, 60])

In [7]:
# (ii) Difference - Diye gye sets main se 1st wale set main 2nd se jo alag hoga wo print hokr aata h

# (a)
np.setdiff1d (n1,n2)

array([10, 20, 30, 40])

In [8]:
# (b)
np.setdiff1d (n2,n1)

array([70, 80, 90])

# (j) Numpy Array Mathematics

In [9]:
# (i) Simple Sum

n1=np.array([10,20,30,40,50])
n2=np.array([50,60,70,80,90])
np.sum ([n1,n2])

500

In [10]:
# (ii) Row wise Sum

np.sum([n1,n2],axis=0)

array([ 60,  80, 100, 120, 140])

In [11]:
# (ii) Column wise Sum

np.sum([n1,n2],axis=1)

array([150, 350])

# (k) Numpy Array Mathematics

In [14]:
# (i) Basic Addition

n1=np.array([45,63,21,12,85])
n1=n1+1
n1

array([46, 64, 22, 13, 86])

In [15]:
n1=np.array([45,63,21,12,85])
n1=n1+7
n1

array([52, 70, 28, 19, 92])

In [16]:
# (ii) Basic Substraction

n1=np.array([45,63,21,12,85])
n1=n1-1
n1

array([44, 62, 20, 11, 84])

In [17]:
n1=np.array([45,63,21,12,85])
n1=n1-7
n1

array([38, 56, 14,  5, 78])

In [19]:
# (iii) Basic Multiplication

n1=np.array([45,63,21,12,85])
n1=n1*2
n1

array([ 90, 126,  42,  24, 170])

In [20]:
n1=np.array([45,63,21,12,85])
n1=n1*7
n1

array([315, 441, 147,  84, 595])

In [21]:
# (iv) Basic Division

n1=np.array([45,63,21,12,85])
n1=n1/2
n1

array([22.5, 31.5, 10.5,  6. , 42.5])

In [22]:
n1=np.array([45,63,21,12,85])
n1=n1/5
n1

array([ 9. , 12.6,  4.2,  2.4, 17. ])

In [23]:
# (v) Mean

n1=np.array([10,20,30,40,50,60])
np.mean(n1)

35.0

In [24]:
n1=np.array([45,63,21,12,85])
np.mean(n1)

45.2

In [25]:
# (vi) Median

n1=np.array([11,44,5,96,67,85])
np.median(n1)

55.5

In [26]:
n1=np.array([45,63,21,12,85])
np.median(n1)

45.0

In [27]:
# (vii) Standard Deviation

n1=np.array([11,44,5,96,67,85])
np.std(n1)

34.644223504391356

In [28]:
n1=np.array([45,63,21,12,85])
np.std(n1)

26.791043279424564

# (l) Numpy Save and Load

In [12]:
# (i) Saving Numpy as np

n1=np.array([10,20,30,40,50,60])
np.save("my_numpy",n1)

In [13]:
# (ii) Loading Numpy Array

n2=np.load("my_numpy.npy")
n2

array([10, 20, 30, 40, 50, 60])